/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 model.glb 
*/

// import React from 'react'
import { useGLTF } from '@react-three/drei'
import type { MathProps, ReactProps, EventHandlers, InstanceProps } from '@react-three/fiber'
import type { Mutable, Overwrite } from '@react-three/fiber/dist/declarations/src/core/utils'
import type { JSX } from 'react/jsx-runtime'
import type { Group, Object3DEventMap } from 'three'
import * as THREE from 'three'
import { COLOURS, type ColourMap } from './palette/colours';


type ModelProps = JSX.IntrinsicAttributes & Mutable<Overwrite<Partial<Overwrite<Group<Object3DEventMap>, MathProps<Group<Object3DEventMap>> & ReactProps<Group<Object3DEventMap>> & Partial<EventHandlers>>>, Omit<InstanceProps<Group<Object3DEventMap>, Group>, "object">>> & {
  color?: string;
};

export function Model(props: ModelProps) {
  const { nodes, materials } = useGLTF(import.meta.env.BASE_URL + 'model.glb')
  const color = props.color || 'red';
  const rgb = COLOURS[color as ColourMap] || COLOURS.red;

  // Clone the material and set its color
  const coloredMaterial = (materials.lambert1.clone() as THREE.MeshLambertMaterial);
  coloredMaterial.color = new THREE.Color(...rgb);

  // Override the material in the meshes
  materials.lambert1 = coloredMaterial;

  return (
    <group {...props} dispose={null} args={[]}>
      <mesh geometry={(nodes.Shell as THREE.Mesh).geometry} material={materials.lambert1} />
      <mesh geometry={(nodes.VME_11003001_LEG_Back_1 as THREE.Mesh).geometry} material={materials.lambert1} />
      <mesh geometry={(nodes.VME_11003001_LEG_Front_1 as THREE.Mesh).geometry} material={materials.lambert1} />
      <mesh geometry={(nodes.knob_01_D_17 as THREE.Mesh).geometry} material={materials.lambert1} position={[0.8, 0, -0.96]} />
      <mesh geometry={(nodes.knob_01_D_18 as THREE.Mesh).geometry} material={materials.lambert1} position={[0, 0, -0.96]} />
      <mesh geometry={(nodes.knob_01_D_19 as THREE.Mesh).geometry} material={materials.lambert1} position={[2.4, -0.8, -0.96]} />
      <mesh geometry={(nodes.knob_01_D_20 as THREE.Mesh).geometry} material={materials.lambert1} position={[1.6, -0.8, -0.96]} />
      <mesh geometry={(nodes.knob_01_D_21 as THREE.Mesh).geometry} material={materials.lambert1} position={[0.8, -0.8, -0.96]} />
      <mesh geometry={(nodes.knob_01_D_22 as THREE.Mesh).geometry} material={materials.lambert1} position={[0, -0.8, -0.96]} />
      <mesh geometry={(nodes.knob_01_D_23 as THREE.Mesh).geometry} material={materials.lambert1} position={[2.4, 0, -0.96]} />
      <mesh geometry={(nodes.knob_01_D_24 as THREE.Mesh).geometry} material={materials.lambert1} position={[1.6, 0, -0.96]} />
      <mesh geometry={(nodes.tube_02_D_7 as THREE.Mesh).geometry} material={materials.lambert1} position={[1.2, -0.4, -0.85]} />
      <mesh geometry={(nodes.tube_02_D_8 as THREE.Mesh).geometry} material={materials.lambert1} position={[2, -0.4, -0.85]} />
      <mesh geometry={(nodes.tube_02_D_9 as THREE.Mesh).geometry} material={materials.lambert1} position={[0.4, -0.4, -0.85]} />
      <mesh geometry={(nodes.tube_02_D_9 as THREE.Mesh).geometry} material={materials.lambert1} position={[0.4, -0.4, -0.85]} />
    </group>
  )
}

useGLTF.preload(import.meta.env.BASE_URL + 'model.glb')
